# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vibeview < Formula
  desc "A local viewer for Claude Code sessions"
  homepage "https://github.com/driangle/vibeview"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.3/vibeview_0.0.3_darwin_amd64.tar.gz"
      sha256 "46c5471b5aad78dba1be8ac502d2c843ca76306073e7011a34e3b16af3617aee"

      define_method(:install) do
        bin.install "vibeview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.3/vibeview_0.0.3_darwin_arm64.tar.gz"
      sha256 "0b6fb62fd1d9311cdb3b75cab08780e12d4de523e91b697379f69cafe41e7faf"

      define_method(:install) do
        bin.install "vibeview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.3/vibeview_0.0.3_linux_amd64.tar.gz"
      sha256 "11e179d8271dedfafb967e6203b595aa4728754b664b16a58f998ee65fa6bf51"
      define_method(:install) do
        bin.install "vibeview"
      end
    end
  end

  test do
    system "#{bin}/vibeview", "-version"
  end
end
