# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vibeview < Formula
  desc "A local viewer for Claude Code sessions"
  homepage "https://github.com/driangle/vibeview"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.9/vibeview_0.0.9_darwin_amd64.tar.gz"
      sha256 "0ab7640316799f352f6797df71864b3c28b708ff6a049220189107cf2f51f2db"

      define_method(:install) do
        bin.install "vibeview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.9/vibeview_0.0.9_darwin_arm64.tar.gz"
      sha256 "90373a2da6a97010aad4f4902da0095f13c1e42afc33848d3295e0ad298dbcb4"

      define_method(:install) do
        bin.install "vibeview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.9/vibeview_0.0.9_linux_amd64.tar.gz"
      sha256 "c3c59e4c59abe830cb8b3c0c5870c686ec727db8105c0eaa0c50ff49a2b3ac47"
      define_method(:install) do
        bin.install "vibeview"
      end
    end
  end

  test do
    system "#{bin}/vibeview", "--version"
  end
end
