# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vibeview < Formula
  desc "A local viewer for Claude Code sessions"
  homepage "https://github.com/driangle/vibeview"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.7/vibeview_0.0.7_darwin_amd64.tar.gz"
      sha256 "d4708eb335a214c92133f04cdf4c487559daf333254ba4dc7b7f089b841d0019"

      define_method(:install) do
        bin.install "vibeview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.7/vibeview_0.0.7_darwin_arm64.tar.gz"
      sha256 "132bdda70a8c0cb180c891b554ce0a8de762bb3ed99a479ead74c15568e320d2"

      define_method(:install) do
        bin.install "vibeview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/driangle/vibeview/releases/download/v0.0.7/vibeview_0.0.7_linux_amd64.tar.gz"
      sha256 "4443e539babf61bddcd4a40ce00240b8c0665e8950595192d1bdf3c682dad092"
      define_method(:install) do
        bin.install "vibeview"
      end
    end
  end

  test do
    system "#{bin}/vibeview", "--version"
  end
end
